#ifndef ATMEGA2560PINMAP_H
#define ATMEGA2560PINMAP_H

// Digital Pins
constexpr uint8_t PIN_PA0 = 22;  // Digital Pin 22 (Port A, Pin 0) - ADC0
constexpr uint8_t PIN_PA1 = 23;  // Digital Pin 23 (Port A, Pin 1) - ADC1
constexpr uint8_t PIN_PA2 = 24;  // Digital Pin 24 (Port A, Pin 2) - ADC2
constexpr uint8_t PIN_PA3 = 25;  // Digital Pin 25 (Port A, Pin 3) - ADC3
constexpr uint8_t PIN_PA4 = 26;  // Digital Pin 26 (Port A, Pin 4) - ADC4
constexpr uint8_t PIN_PA5 = 27;  // Digital Pin 27 (Port A, Pin 5) - ADC5
constexpr uint8_t PIN_PA6 = 28;  // Digital Pin 28 (Port A, Pin 6)
constexpr uint8_t PIN_PA7 = 29;  // Digital Pin 29 (Port A, Pin 7)
constexpr uint8_t PIN_PB0 = 53;  // Digital Pin 53 (Port B, Pin 0)
constexpr uint8_t PIN_PB1 = 52;  // Digital Pin 52 (Port B, Pin 1)
constexpr uint8_t PIN_PB2 = 51;  // Digital Pin 51 (Port B, Pin 2)
constexpr uint8_t PIN_PB3 = 50;  // Digital Pin 50 (Port B, Pin 3)
constexpr uint8_t PIN_PB4 = 10;  // Digital Pin 10 (Port B, Pin 4) - SS
constexpr uint8_t PIN_PB5 = 11;  // Digital Pin 11 (Port B, Pin 5) - MOSI
constexpr uint8_t PIN_PB6 = 12;  // Digital Pin 12 (Port B, Pin 6) - MISO
constexpr uint8_t PIN_PB7 = 13;  // Digital Pin 13 (Port B, Pin 7) - SCK
constexpr uint8_t PIN_PC0 = 37;  // Digital Pin 37 (Port C, Pin 0)
constexpr uint8_t PIN_PC1 = 36;  // Digital Pin 36 (Port C, Pin 1)
constexpr uint8_t PIN_PC2 = 35;  // Digital Pin 35 (Port C, Pin 2)
constexpr uint8_t PIN_PC3 = 34;  // Digital Pin 34 (Port C, Pin 3)
constexpr uint8_t PIN_PC4 = 33;  // Digital Pin 33 (Port C, Pin 4)
constexpr uint8_t PIN_PC5 = 32;  // Digital Pin 32 (Port C, Pin 5)
constexpr uint8_t PIN_PC6 = 31;  // Digital Pin 31 (Port C, Pin 6)
constexpr uint8_t PIN_PC7 = 30;  // Digital Pin 30 (Port C, Pin 7)
constexpr uint8_t PIN_PD0 = 0;   // Digital Pin 0 (Port D, Pin 0) - RXD0
constexpr uint8_t PIN_PD1 = 1;   // Digital Pin 1 (Port D, Pin 1) - TXD0
constexpr uint8_t PIN_PD2 = 2;   // Digital Pin 2 (Port D, Pin 2) - RXD1
constexpr uint8_t PIN_PD3 = 3;   // Digital Pin 3 (Port D, Pin 3) - TXD1
constexpr uint8_t PIN_PD4 = 4;   // Digital Pin 4 (Port D, Pin 4)
constexpr uint8_t PIN_PD5 = 5;   // Digital Pin 5 (Port D, Pin 5)
constexpr uint8_t PIN_PD6 = 6;   // Digital Pin 6 (Port D, Pin 6)
constexpr uint8_t PIN_PD7 = 7;   // Digital Pin 7 (Port D, Pin 7)
constexpr uint8_t PIN_PE0 = 22;  // Digital Pin 22 (Port E, Pin 0) - RXD2
constexpr uint8_t PIN_PE1 = 21;  // Digital Pin 21 (Port E, Pin 1) - TXD2
constexpr uint8_t PIN_PE2 = 20;  // Digital Pin 20 (Port E, Pin 2) - RXD3
constexpr uint8_t PIN_PE3 = 19;  // Digital Pin 19 (Port E, Pin 3) - TXD3
constexpr uint8_t PIN_PE4 = 18;  // Digital Pin 18 (Port E, Pin 4)
constexpr uint8_t PIN_PE5 = 17;  // Digital Pin 17 (Port E, Pin 5)
constexpr uint8_t PIN_PE6 = 16;  // Digital Pin 16 (Port E, Pin 6)
constexpr uint8_t PIN_PF0 = 0;   // Digital Pin 0 (Port F, Pin 0) - AREF
constexpr uint8_t PIN_PF1 = 1;   // Digital Pin 1 (Port F, Pin 1)
constexpr uint8_t PIN_PF2 = 2;   // Digital Pin 2 (Port F, Pin 2)
constexpr uint8_t PIN_PF3 = 3;   // Digital Pin 3 (Port F, Pin 3)
constexpr uint8_t PIN_PF4 = 4;   // Digital Pin 4 (Port F, Pin 4)
constexpr uint8_t PIN_PF5 = 5;   // Digital Pin 5 (Port F, Pin 5)
constexpr uint8_t PIN_PF6 = 6;   // Digital Pin 6 (Port F, Pin 6)
constexpr uint8_t PIN_PF7 = 7;   // Digital Pin 7 (Port F, Pin 7)
constexpr uint8_t PIN_PG0 = 0;   // Digital Pin 0 (Port G, Pin 0) - RXD3
constexpr uint8_t PIN_PG1 = 1;   // Digital Pin 1 (Port G, Pin 1) - TXD3
constexpr uint8_t PIN_PG2 = 2;   // Digital Pin 2 (Port G, Pin 2)
constexpr uint8_t PIN_PG3 = 3;   // Digital Pin 3 (Port G, Pin 3)
constexpr uint8_t PIN_PG4 = 4;   // Digital Pin 4 (Port G, Pin 4)
constexpr uint8_t PIN_PG5 = 5;   // Digital Pin 5 (Port G, Pin 5)
constexpr uint8_t PIN_PG6 = 6;   // Digital Pin 6 (Port G, Pin 6)
constexpr uint8_t PIN_PG7 = 7;   // Digital Pin 7 (Port G, Pin 7)
constexpr uint8_t PIN_PH0 = 8;   // Digital Pin 8 (Port H, Pin 0)
constexpr uint8_t PIN_PH1 = 9;   // Digital Pin 9 (Port H, Pin 1)
constexpr uint8_t PIN_PH2 = 10;  // Digital Pin 10 (Port H, Pin 2)
constexpr uint8_t PIN_PH3 = 11;  // Digital Pin 11 (Port H, Pin 3)
constexpr uint8_t PIN_PH4 = 12;  // Digital Pin 12 (Port H, Pin 4)
constexpr uint8_t PIN_PH5 = 13;  // Digital Pin 13 (Port H, Pin 5)
constexpr uint8_t PIN_PH6 = 14;  // Digital Pin 14 (Port H, Pin 6)
constexpr uint8_t PIN_PH7 = 15;  // Digital Pin 15 (Port H, Pin 7)
constexpr uint8_t PIN_PJ0 = 0;   // Digital Pin 0 (Port J, Pin 0)
constexpr uint8_t PIN_PJ1 = 1;   // Digital Pin 1 (Port J, Pin 1)
constexpr uint8_t PIN_PJ2 = 2;   // Digital Pin 2 (Port J, Pin 2)
constexpr uint8_t PIN_PJ3 = 3;   // Digital Pin 3 (Port J, Pin 3)
constexpr uint8_t PIN_PJ4 = 4;   // Digital Pin 4 (Port J, Pin 4)
constexpr uint8_t PIN_PJ5 = 5;   // Digital Pin 5 (Port J, Pin 5)
constexpr uint8_t PIN_PJ6 = 6;   // Digital Pin 6 (Port J, Pin 6)
constexpr uint8_t PIN_PJ7 = 7;   // Digital Pin 7 (Port J, Pin 7)
constexpr uint8_t PIN_PK0 = 0;   // Digital Pin 0 (Port K, Pin 0)
constexpr uint8_t PIN_PK1 = 1;   // Digital Pin 1 (Port K, Pin 1)
constexpr uint8_t PIN_PK2 = 2;   // Digital Pin 2 (Port K, Pin 2)
constexpr uint8_t PIN_PK3 = 3;   // Digital Pin 3 (Port K, Pin 3)
constexpr uint8_t PIN_PK4 = 4;   // Digital Pin 4 (Port K, Pin 4)
constexpr uint8_t PIN_PK5 = 5;   // Digital Pin 5 (Port K, Pin 5)
constexpr uint8_t PIN_PK6 = 6;   // Digital Pin 6 (Port K, Pin 6)
constexpr uint8_t PIN_PK7 = 7;   // Digital Pin 7 (Port K, Pin 7)
constexpr uint8_t PIN_PL0 = 0;   // Digital Pin 0 (Port L, Pin 0)
constexpr uint8_t PIN_PL1 = 1;   // Digital Pin 1 (Port L, Pin 1)
constexpr uint8_t PIN_PL2 = 2;   // Digital Pin 2 (Port L, Pin 2)
constexpr uint8_t PIN_PL3 = 3;   // Digital Pin 3 (Port L, Pin 3)
constexpr uint8_t PIN_PL4 = 4;   // Digital Pin 4 (Port L, Pin 4)
constexpr uint8_t PIN_PL5 = 5;   // Digital Pin 5 (Port L, Pin 5)
constexpr uint8_t PIN_PL6 = 6;   // Digital Pin 6 (Port L, Pin 6)
constexpr uint8_t PIN_PL7 = 7;   // Digital Pin 7 (Port L, Pin 7)

#endif // ATMEGA2560PINMAP_H
